# render.yaml - Blueprint for Render deployment
services:
  - type: web
    name: agriprice-prophet-api
    runtime: python
    repo: https://github.com/dahamkakooza/Summative-assignment---MLOP_Kakooza-Mahad.git
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ENVIRONMENT
        value: production
